import "../styles/globals.css"
import { Inter } from "next/font/google"
import { FiltersProvider } from "@/contexts/filtersContext"
import { CartProvider } from "@/contexts/cart"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "AtheShop",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
            <CartProvider>
              <FiltersProvider>
                {children}
              </FiltersProvider>
            </CartProvider>
      </body>
    </html>
  )
}
