import "../styles/globals.css"
import { Header } from "@/components/header/Header"
import { Inter } from "next/font/google"
import { FiltersProvider } from "@/contexts/filtersContext"
import { CartProvider } from "@/contexts/cart"
import { UserProvider } from "@/contexts/user"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "AtheShop",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <UserProvider>
            <CartProvider>
              <FiltersProvider>
                {/* <Header /> */}
                {children}
              </FiltersProvider>
            </CartProvider>
          </UserProvider>
      </body>
    </html>
  )
}
